name: CI
on: push
jobs:
  lint:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run shellcheck
        run: ./run lint
  test:
    strategy:
      matrix:
        include:
          - name: linux
            runner_os: ubuntu-latest
          - name: mac
            runner_os: macos-latest
    runs-on: ${{ matrix.runner_os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install test runner
        run: npm install -g bats
      - name: Run tests
        run: ./run test
